//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolumeTrayAppWPF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolumeTrayAppWPF.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argb hex:.
        /// </summary>
        public static string ColorPicker_ArgbHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_ArgbHexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Alpha {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string ColorPicker_ChannelLabel_B {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string ColorPicker_ChannelLabel_G {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hue.
        /// </summary>
        public static string ColorPicker_ChannelLabel_Hue {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string ColorPicker_ChannelLabel_R {
            get {
                return ResourceManager.GetString("ColorPicker_ChannelLabel_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ColorPicker_CloseTooltip {
            get {
                return ResourceManager.GetString("ColorPicker_CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ColorPicker_DefaultButton {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker.
        /// </summary>
        public static string ColorPicker_DefaultTitle {
            get {
                return ResourceManager.GetString("ColorPicker_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ColorPicker_ResetButton {
            get {
                return ResourceManager.GetString("ColorPicker_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgba hex:.
        /// </summary>
        public static string ColorPicker_RgbaHexLabel {
            get {
                return ResourceManager.GetString("ColorPicker_RgbaHexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click: set as default. Ctrl+click: enable / disable. Shift+click: set as default communications..
        /// </summary>
        public static string Flyout_DeviceIcon_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_DeviceIcon_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click: toggle Listen to this device. Ctrl+click: enable with Default Playback target. Right-click: pick target device..
        /// </summary>
        public static string Flyout_ListenButton_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_ListenButton_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default Playback Device.
        /// </summary>
        public static string Flyout_ListenMenu_DefaultPlaybackDevice {
            get {
                return ResourceManager.GetString("Flyout_ListenMenu_DefaultPlaybackDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redock.
        /// </summary>
        public static string Flyout_Redock_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_Redock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Flyout_Settings_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_Settings_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undock.
        /// </summary>
        public static string Flyout_Undock_Tooltip {
            get {
                return ResourceManager.GetString("Flyout_Undock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Settings_About_AuthorLabel {
            get {
                return ResourceManager.GetString("Settings_About_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Settings_About_BuildLabel {
            get {
                return ResourceManager.GetString("Settings_About_BuildLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Settings_About_GithubLabel {
            get {
                return ResourceManager.GetString("Settings_About_GithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Settings_About_RuntimeLabel {
            get {
                return ResourceManager.GetString("Settings_About_RuntimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_About_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A WPF tray app skeleton..
        /// </summary>
        public static string Settings_About_Tagline {
            get {
                return ResourceManager.GetString("Settings_About_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_Common_Tab_About {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Settings_Common_Tab_Devices {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Common_Tab_Flyout {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_Flyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_Common_Tab_General {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Settings_Common_Tab_Hotkeys {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Common_Tab_Theme {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Icon.
        /// </summary>
        public static string Settings_Common_Tab_TrayIcon {
            get {
                return ResourceManager.GetString("Settings_Common_Tab_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaulting.
        /// </summary>
        public static string Settings_Devices_Defaulting_Header {
            get {
                return ResourceManager.GetString("Settings_Devices_Defaulting_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording visibility.
        /// </summary>
        public static string Settings_Devices_RecordingVisibility_Header {
            get {
                return ResourceManager.GetString("Settings_Devices_RecordingVisibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Settings_Devices_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Devices_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you set a default device through this app, also promote it to the communications-role default. Only triggered by your own clicks; never reacts to other apps&apos; default-changes..
        /// </summary>
        public static string Settings_Devices_SetDefaultCommsToDefault_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_SetDefaultCommsToDefault_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie default comms device to default device.
        /// </summary>
        public static string Settings_Devices_SetDefaultCommsToDefault_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_SetDefaultCommsToDefault_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always include the communications-role default playback device, even when it&apos;s disabled in Windows..
        /// </summary>
        public static string Settings_Devices_ShowDefaultCommsPlaybackEvenIfDisabled_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultCommsPlaybackEvenIfDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show default comms playback device even if disabled.
        /// </summary>
        public static string Settings_Devices_ShowDefaultCommsPlaybackEvenIfDisabled_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultCommsPlaybackEvenIfDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always include the communications-role default recording device, even when it&apos;s disabled in Windows..
        /// </summary>
        public static string Settings_Devices_ShowDefaultCommsRecordingEvenIfDisabled_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultCommsRecordingEvenIfDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show default comms recording device even if disabled.
        /// </summary>
        public static string Settings_Devices_ShowDefaultCommsRecordingEvenIfDisabled_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultCommsRecordingEvenIfDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always include the default playback device in lists, even when it&apos;s disabled in Windows..
        /// </summary>
        public static string Settings_Devices_ShowDefaultPlaybackEvenIfDisabled_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultPlaybackEvenIfDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show default playback device even if disabled.
        /// </summary>
        public static string Settings_Devices_ShowDefaultPlaybackEvenIfDisabled_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultPlaybackEvenIfDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always include the default recording device, even when it&apos;s disabled in Windows..
        /// </summary>
        public static string Settings_Devices_ShowDefaultRecordingEvenIfDisabled_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultRecordingEvenIfDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show default recording device even if disabled.
        /// </summary>
        public static string Settings_Devices_ShowDefaultRecordingEvenIfDisabled_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDefaultRecordingEvenIfDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List playback devices that are disabled in Windows. Off by default..
        /// </summary>
        public static string Settings_Devices_ShowDisabledPlayback_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDisabledPlayback_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show disabled playback devices.
        /// </summary>
        public static string Settings_Devices_ShowDisabledPlayback_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDisabledPlayback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List recording devices that are disabled in Windows..
        /// </summary>
        public static string Settings_Devices_ShowDisabledRecording_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDisabledRecording_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show disabled recording devices.
        /// </summary>
        public static string Settings_Devices_ShowDisabledRecording_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDisabledRecording_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List playback devices Windows reports as currently unplugged but still recognized. Registry-only ghost endpoints have their own setting below..
        /// </summary>
        public static string Settings_Devices_ShowDisconnectedPlayback_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDisconnectedPlayback_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show disconnected playback devices.
        /// </summary>
        public static string Settings_Devices_ShowDisconnectedPlayback_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowDisconnectedPlayback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List endpoints Windows still has on file but no driver is currently loaded for - old USB DACs, removed GPUs&apos; HDMI outputs, paired Bluetooth headsets. Most surface as &quot;Unknown Device&quot;. Off by default..
        /// </summary>
        public static string Settings_Devices_ShowNotPresent_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowNotPresent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show registry ghost devices.
        /// </summary>
        public static string Settings_Devices_ShowNotPresent_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowNotPresent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master switch for recording-device entries. When off, every recording-side option below is ignored..
        /// </summary>
        public static string Settings_Devices_ShowRecording_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowRecording_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recording devices.
        /// </summary>
        public static string Settings_Devices_ShowRecording_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowRecording_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an entry that opens the classic Sound control panel on the Communications tab..
        /// </summary>
        public static string Settings_Devices_ShowTrayCommunicationsLink_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTrayCommunicationsLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Communications&quot; link in tray menu.
        /// </summary>
        public static string Settings_Devices_ShowTrayCommunicationsLink_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTrayCommunicationsLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a sub-menu entry per visible enabled device. Each entry opens the matching classic Sound tab (same as Ctrl+click on the device icon in the flyout)..
        /// </summary>
        public static string Settings_Devices_ShowTrayDeviceLinks_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTrayDeviceLinks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show per-device links in tray menu.
        /// </summary>
        public static string Settings_Devices_ShowTrayDeviceLinks_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTrayDeviceLinks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an entry that opens the classic Sound control panel on the Recording tab..
        /// </summary>
        public static string Settings_Devices_ShowTrayRecordingLink_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTrayRecordingLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Recording&quot; link in tray menu.
        /// </summary>
        public static string Settings_Devices_ShowTrayRecordingLink_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTrayRecordingLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an entry that opens the classic Sound control panel on the Sounds tab..
        /// </summary>
        public static string Settings_Devices_ShowTraySoundsLink_Description {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTraySoundsLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Sounds&quot; link in tray menu.
        /// </summary>
        public static string Settings_Devices_ShowTraySoundsLink_Title {
            get {
                return ResourceManager.GetString("Settings_Devices_ShowTraySoundsLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray menu.
        /// </summary>
        public static string Settings_Devices_TrayMenu_Header {
            get {
                return ResourceManager.GetString("Settings_Devices_TrayMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback visibility.
        /// </summary>
        public static string Settings_Devices_Visibility_Header {
            get {
                return ResourceManager.GetString("Settings_Devices_Visibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps above device.
        /// </summary>
        public static string Settings_Flyout_DeviceLayout_AppsAbove {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceLayout_AppsAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps below device.
        /// </summary>
        public static string Settings_Flyout_DeviceLayout_AppsBelow {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceLayout_AppsBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where each device&apos;s row sits relative to its app sliders..
        /// </summary>
        public static string Settings_Flyout_DeviceLayout_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device layout.
        /// </summary>
        public static string Settings_Flyout_DeviceLayout_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceLayout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list.
        /// </summary>
        public static string Settings_Flyout_DeviceList_Header {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default sort: default, default communications, enabled, disabled, disconnected. The default device sits at the bottom of the flyout. Windows sort: untouched MMDevice enumeration order..
        /// </summary>
        public static string Settings_Flyout_DeviceSort_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceSort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Flyout_DeviceSort_StateGrouped {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceSort_StateGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device sort.
        /// </summary>
        public static string Settings_Flyout_DeviceSort_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceSort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows order.
        /// </summary>
        public static string Settings_Flyout_DeviceSort_WindowsEnumeration {
            get {
                return ResourceManager.GetString("Settings_Flyout_DeviceSort_WindowsEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on, recording devices interleave with playback devices inside each sort bucket. When off, all playback devices show first and recording devices group together at the top of the list..
        /// </summary>
        public static string Settings_Flyout_IntermixRecording_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_IntermixRecording_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show "Listen to this device" button.
        /// </summary>
        public static string Settings_Flyout_ShowListenButton_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowListenButton_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adds a button to each recording device row that toggles the Windows "Listen to this device" feature..
        /// </summary>
        public static string Settings_Flyout_ShowListenButton_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowListenButton_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Intermix recording with playback.
        /// </summary>
        public static string Settings_Flyout_IntermixRecording_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_IntermixRecording_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the app launches, restore the flyout&apos;s docked or undocked state from the previous session. When off, the flyout always opens docked..
        /// </summary>
        public static string Settings_Flyout_RestoreUndockState_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_RestoreUndockState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore undock state on startup.
        /// </summary>
        public static string Settings_Flyout_RestoreUndockState_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_RestoreUndockState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout.
        /// </summary>
        public static string Settings_Flyout_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Flyout_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include capture endpoints (microphones, line-in) in the flyout&apos;s device list. Still gated by the global recording-devices toggle on the Devices page..
        /// </summary>
        public static string Settings_Flyout_ShowRecordingDevices_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowRecordingDevices_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recording devices.
        /// </summary>
        public static string Settings_Flyout_ShowRecordingDevices_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowRecordingDevices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the undock button in the flyout. When off, the flyout always stays anchored to the tray..
        /// </summary>
        public static string Settings_Flyout_ShowUndockButton_Description {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowUndockButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show undock button.
        /// </summary>
        public static string Settings_Flyout_ShowUndockButton_Title {
            get {
                return ResourceManager.GetString("Settings_Flyout_ShowUndockButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Settings_Flyout_Visibility_Header {
            get {
                return ResourceManager.GetString("Settings_Flyout_Visibility_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_General_Apply_Button {
            get {
                return ResourceManager.GetString("Settings_General_Apply_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save changes..
        /// </summary>
        public static string Settings_General_Autosave_Description {
            get {
                return ResourceManager.GetString("Settings_General_Autosave_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save.
        /// </summary>
        public static string Settings_General_Autosave_Title {
            get {
                return ResourceManager.GetString("Settings_General_Autosave_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App icons.
        /// </summary>
        public static string Settings_General_AppIcons_Header {
            get {
                return ResourceManager.GetString("Settings_General_AppIcons_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_General_Cancel_Button {
            get {
                return ResourceManager.GetString("Settings_General_Cancel_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currently running from &quot;{0}&quot;..
        /// </summary>
        public static string Settings_General_CurrentlyRunning_Format {
            get {
                return ResourceManager.GetString("Settings_General_CurrentlyRunning_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wait between attempts when an app icon fails to resolve. Four attempts run with linear backoff (1x, 2x, 3x this value), so the worst case with the default is roughly 1.5 seconds before the fallback glyph stays..
        /// </summary>
        public static string Settings_General_IconRetryInterval_Description {
            get {
                return ResourceManager.GetString("Settings_General_IconRetryInterval_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon retry interval (ms).
        /// </summary>
        public static string Settings_General_IconRetryInterval_Title {
            get {
                return ResourceManager.GetString("Settings_General_IconRetryInterval_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Settings_General_Install_Button {
            get {
                return ResourceManager.GetString("Settings_General_Install_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Settings_General_Installation_Header {
            get {
                return ResourceManager.GetString("Settings_General_Installation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will copy the running exe to &quot;{0}&quot; and register it in Windows Settings &gt; Apps..
        /// </summary>
        public static string Settings_General_InstallConfirm_Message_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstallConfirm_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install VolumeTrayAppWPF?.
        /// </summary>
        public static string Settings_General_InstallConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed at &quot;{0}&quot;..
        /// </summary>
        public static string Settings_General_Installed_Format {
            get {
                return ResourceManager.GetString("Settings_General_Installed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed (older build) at &quot;{0}&quot;.{1}.
        /// </summary>
        public static string Settings_General_InstalledOlderBuild_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledOlderBuild_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed build {0}, running build {1}. Click Update to overwrite.{2}.
        /// </summary>
        public static string Settings_General_InstalledOutOfDate_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledOutOfDate_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed (build {0}) at &quot;{1}&quot;..
        /// </summary>
        public static string Settings_General_InstalledWithBuild_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstalledWithBuild_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install failed.
        /// </summary>
        public static string Settings_General_InstallFailed_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will copy the running exe to &quot;{0}&quot; and register it in Windows Settings &gt; Apps. Requires admin..
        /// </summary>
        public static string Settings_General_InstallSystemWideConfirm_Message_Format {
            get {
                return ResourceManager.GetString("Settings_General_InstallSystemWideConfirm_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install VolumeTrayAppWPF system-wide?.
        /// </summary>
        public static string Settings_General_InstallSystemWideConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_General_InstallSystemWideConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local user.
        /// </summary>
        public static string Settings_General_LocalUser_Title {
            get {
                return ResourceManager.GetString("Settings_General_LocalUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map the slider to volume on a perceptual curve so equal slider deltas feel like equal loudness deltas..
        /// </summary>
        public static string Settings_General_LogarithmicVolumeScale_Description {
            get {
                return ResourceManager.GetString("Settings_General_LogarithmicVolumeScale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use logarithmic volume scale.
        /// </summary>
        public static string Settings_General_LogarithmicVolumeScale_Title {
            get {
                return ResourceManager.GetString("Settings_General_LogarithmicVolumeScale_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Settings_General_Notifications_Header {
            get {
                return ResourceManager.GetString("Settings_General_Notifications_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed. Will be placed at &quot;{0}&quot;.{1}.
        /// </summary>
        public static string Settings_General_NotInstalled_Format {
            get {
                return ResourceManager.GetString("Settings_General_NotInstalled_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter.
        /// </summary>
        public static string Settings_General_PeakMeter_Header {
            get {
                return ResourceManager.GetString("Settings_General_PeakMeter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a Windows notification sound when you change a per-app slider, scaled to the app&apos;s mixed volume so quieter apps preview quieter..
        /// </summary>
        public static string Settings_General_PlayAppVolumeChangeSound_Description {
            get {
                return ResourceManager.GetString("Settings_General_PlayAppVolumeChangeSound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when changing app volume.
        /// </summary>
        public static string Settings_General_PlayAppVolumeChangeSound_Title {
            get {
                return ResourceManager.GetString("Settings_General_PlayAppVolumeChangeSound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the Windows default beep when you change the volume on the device slider. Per-app sliders stay silent..
        /// </summary>
        public static string Settings_General_PlayDeviceVolumeChangeSound_Description {
            get {
                return ResourceManager.GetString("Settings_General_PlayDeviceVolumeChangeSound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when changing device volume.
        /// </summary>
        public static string Settings_General_PlayDeviceVolumeChangeSound_Title {
            get {
                return ResourceManager.GetString("Settings_General_PlayDeviceVolumeChangeSound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (requires admin).
        /// </summary>
        public static string Settings_General_RequiresAdmin_Suffix {
            get {
                return ResourceManager.GetString("Settings_General_RequiresAdmin_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch VolumeTrayAppWPF when you sign in to Windows..
        /// </summary>
        public static string Settings_General_RunOnStartup_Description {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Target: {1}.
        /// </summary>
        public static string Settings_General_RunOnStartup_OnDescriptionFormat {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_OnDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart shortcut placed in shell:startup..
        /// </summary>
        public static string Settings_General_RunOnStartup_OnHeaderLine {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_OnHeaderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on startup automatically.
        /// </summary>
        public static string Settings_General_RunOnStartup_Title {
            get {
                return ResourceManager.GetString("Settings_General_RunOnStartup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Settings_General_Seconds_Suffix {
            get {
                return ResourceManager.GetString("Settings_General_Seconds_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_General_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System wide.
        /// </summary>
        public static string Settings_General_SystemWide_Title {
            get {
                return ResourceManager.GetString("Settings_General_SystemWide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Settings_General_Uninstall_Button {
            get {
                return ResourceManager.GetString("Settings_General_Uninstall_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall completed with warnings. Some files or registry entries may need manual removal. Check the install location and Windows Settings &gt; Apps..
        /// </summary>
        public static string Settings_General_UninstallIncomplete_Message {
            get {
                return ResourceManager.GetString("Settings_General_UninstallIncomplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall incomplete.
        /// </summary>
        public static string Settings_General_UninstallIncomplete_Title {
            get {
                return ResourceManager.GetString("Settings_General_UninstallIncomplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Settings_General_Update_Button {
            get {
                return ResourceManager.GetString("Settings_General_Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Settings_Hotkeys_Add_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete this hotkey.
        /// </summary>
        public static string Settings_Hotkeys_DeleteHotkey_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_DeleteHotkey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Settings_Hotkeys_Exists_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Exists_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Settings_Hotkeys_Key_Enter {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string Settings_Hotkeys_Key_Escape {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageDown.
        /// </summary>
        public static string Settings_Hotkeys_Key_PageDown {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageUp.
        /// </summary>
        public static string Settings_Hotkeys_Key_PageUp {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Settings_Hotkeys_Key_Space {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Key_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Alt {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_AltWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_AltWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Ctrl {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAlt {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlAltWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlAltWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlShift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_CtrlWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_CtrlWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Shift {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_ShiftWin {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_ShiftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Settings_Hotkeys_Modifier_Win {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Modifier_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this settings window..
        /// </summary>
        public static string Settings_Hotkeys_OpenSettings_Description {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string Settings_Hotkeys_OpenSettings_Title {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_OpenSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Settings_Hotkeys_Remove_Button {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Settings_Hotkeys_SearchLabel {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind a system-wide keyboard shortcut to each action. Bindings require at least one modifier key (Ctrl, Alt, Shift, or Win). All actions start unbound..
        /// </summary>
        public static string Settings_Hotkeys_SectionDescription {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        public static string Settings_Hotkeys_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey service not available..
        /// </summary>
        public static string Settings_Hotkeys_Status_HotkeyServiceUnavailable {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Status_HotkeyServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered..
        /// </summary>
        public static string Settings_Hotkeys_Status_Registered {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Status_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Theme_Appearance_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Appearance_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the default background color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Settings_Theme_BackgroundColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the overall size of the tray context menu. All elements scale from font size..
        /// </summary>
        public static string Settings_Theme_FontSize_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_FontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string Settings_Theme_FontSize_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_FontSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter.
        /// </summary>
        public static string Settings_Theme_MeterPeak_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeak_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount, in volume units (0 to 100), that the peak meter can move in a single redraw. Caps single-frame jumps so a sudden silence-to-loud transition ramps over a few frames. 0 freezes the meter; 100 disables the cap..
        /// </summary>
        public static string Settings_Theme_MeterPeakChangeCeiling_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakChangeCeiling_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter change ceiling.
        /// </summary>
        public static string Settings_Theme_MeterPeakChangeCeiling_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakChangeCeiling_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the peak meter overlay drawn on top of the volume slider track..
        /// </summary>
        public static string Settings_Theme_MeterPeakColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter color.
        /// </summary>
        public static string Settings_Theme_MeterPeakColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit peak meter color.
        /// </summary>
        public static string Settings_Theme_MeterPeakColor_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakColor_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often the meter is redrawn. Higher than the sample rate buys smoothness via linear interpolation between samples; equal to the sample rate snaps with no interpolation..
        /// </summary>
        public static string Settings_Theme_MeterPeakFps_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakFps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter refresh rate (FPS).
        /// </summary>
        public static string Settings_Theme_MeterPeakFps_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakFps_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often the raw audio peak is read from Windows. Lower than the refresh rate to enable smoothing; higher than the refresh rate wastes CPU..
        /// </summary>
        public static string Settings_Theme_MeterPeakSampleRate_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakSampleRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter sample rate.
        /// </summary>
        public static string Settings_Theme_MeterPeakSampleRate_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakSampleRate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the stereo overlay drawn on top of the base bar to the loudest channel. Translucent by default so the channel mismatch reads as a halo extending past the base..
        /// </summary>
        public static string Settings_Theme_MeterPeakStereoColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakStereoColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak meter stereo color.
        /// </summary>
        public static string Settings_Theme_MeterPeakStereoColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakStereoColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit peak meter stereo color.
        /// </summary>
        public static string Settings_Theme_MeterPeakStereoColor_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_MeterPeakStereoColor_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string Settings_Theme_PickerTitle_DarkVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_DarkVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Settings_Theme_PickerTitle_Format {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        public static string Settings_Theme_PickerTitle_LightVariant {
            get {
                return ResourceManager.GetString("Settings_Theme_PickerTitle_LightVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_Theme_Reset {
            get {
                return ResourceManager.GetString("Settings_Theme_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies rounded corners to the flyout, settings cards, buttons, and menus. Turn off for a squared-off look..
        /// </summary>
        public static string Settings_Theme_RoundedCorners_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_RoundedCorners_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounded corners.
        /// </summary>
        public static string Settings_Theme_RoundedCorners_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_RoundedCorners_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_Theme_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape drawn as the volume-slider thumb. Each option keeps its own font and proportions..
        /// </summary>
        public static string Settings_Theme_SliderIndicator_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_SliderIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider indicator.
        /// </summary>
        public static string Settings_Theme_SliderIndicator_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_SliderIndicator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme text color.
        /// </summary>
        public static string Settings_Theme_TextColor_DarkTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_DarkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the default text color. Each variant falls back to the default when unset..
        /// </summary>
        public static string Settings_Theme_TextColor_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme text color.
        /// </summary>
        public static string Settings_Theme_TextColor_LightTooltip {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_LightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string Settings_Theme_TextColor_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_TextColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Windows, or force light / dark mode for this app..
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_System {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme style.
        /// </summary>
        public static string Settings_Theme_ThemeStyle_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_ThemeStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How strongly the quieter channel weights the combined value. 0 keeps the louder channel; 1 averages the channels; higher values dampen stereo flutter by biasing the result toward the quieter channel..
        /// </summary>
        public static string Settings_Theme_UnifiedMeterBias_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_UnifiedMeterBias_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified meter low channel bias multiplier.
        /// </summary>
        public static string Settings_Theme_UnifiedMeterBias_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_UnifiedMeterBias_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine the left and right channels into a single weighted bar instead of drawing the stereo overlay on top of the base meter..
        /// </summary>
        public static string Settings_Theme_UnifiedPeakMeter_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_UnifiedPeakMeter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified peak meter.
        /// </summary>
        public static string Settings_Theme_UnifiedPeakMeter_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_UnifiedPeakMeter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + double left click.
        /// </summary>
        public static string Settings_TrayIcon_AltDoubleLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_AltDoubleLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + left click.
        /// </summary>
        public static string Settings_TrayIcon_AltLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_AltLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt + right click.
        /// </summary>
        public static string Settings_TrayIcon_AltRightClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_AltRightClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Settings_TrayIcon_ClickAction_Nothing {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ClickAction_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu.
        /// </summary>
        public static string Settings_TrayIcon_ContextMenu_Header {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ContextMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + double left click.
        /// </summary>
        public static string Settings_TrayIcon_CtrlDoubleLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_CtrlDoubleLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + left click.
        /// </summary>
        public static string Settings_TrayIcon_CtrlLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_CtrlLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + right click.
        /// </summary>
        public static string Settings_TrayIcon_CtrlRightClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_CtrlRightClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Settings_TrayIcon_DeviceName_Model {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DeviceName_Model", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Settings_TrayIcon_DeviceName_Name {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DeviceName_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name+Model.
        /// </summary>
        public static string Settings_TrayIcon_DeviceName_NameAndModel {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DeviceName_NameAndModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Names longer than this character count are truncated with a 2-dot ellipsis suffix..
        /// </summary>
        public static string Settings_TrayIcon_DeviceNameMaxLength_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DeviceNameMaxLength_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device name max length.
        /// </summary>
        public static string Settings_TrayIcon_DeviceNameMaxLength_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DeviceNameMaxLength_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double left click.
        /// </summary>
        public static string Settings_TrayIcon_DoubleLeftClick_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_DoubleLeftClick_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Classic {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic opens at the cursor. Modern docks the menu above the taskbar like the Windows 11 system flyouts..
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Modern {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu position.
        /// </summary>
        public static string Settings_TrayIcon_MenuPosition_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MenuPosition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign actions to modified clicks on the tray icon. Entries set to Nothing fall back to the default behavior..
        /// </summary>
        public static string Settings_TrayIcon_ModifiedActions_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ModifiedActions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified actions.
        /// </summary>
        public static string Settings_TrayIcon_ModifiedActions_Header {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_ModifiedActions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll the mouse wheel over the tray icon to adjust the default device&apos;s volume. Does *not* use an always-active global mouse hook..
        /// </summary>
        public static string Settings_TrayIcon_MouseWheel_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MouseWheel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse wheel.
        /// </summary>
        public static string Settings_TrayIcon_MouseWheel_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_MouseWheel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Which slice of each playback device&apos;s name appears in the tray context menu..
        /// </summary>
        public static string Settings_TrayIcon_PlaybackDeviceName_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_PlaybackDeviceName_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playback device names.
        /// </summary>
        public static string Settings_TrayIcon_PlaybackDeviceName_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_PlaybackDeviceName_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Which slice of each recording device&apos;s name appears in the tray context menu..
        /// </summary>
        public static string Settings_TrayIcon_RecordingDeviceName_Description {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_RecordingDeviceName_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recording device names.
        /// </summary>
        public static string Settings_TrayIcon_RecordingDeviceName_Title {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_RecordingDeviceName_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tray Icon.
        /// </summary>
        public static string Settings_TrayIcon_SectionHeader {
            get {
                return ResourceManager.GetString("Settings_TrayIcon_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsWindow_Caption_Close {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string SettingsWindow_Caption_Maximize {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string SettingsWindow_Caption_Minimize {
            get {
                return ResourceManager.GetString("SettingsWindow_Caption_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_Confirm {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_DefaultMessage {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all saved display data?.
        /// </summary>
        public static string SettingsWindow_ConfirmOverlay_DefaultTitle {
            get {
                return ResourceManager.GetString("SettingsWindow_ConfirmOverlay_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Header {
            get {
                return ResourceManager.GetString("SettingsWindow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings folder.
        /// </summary>
        public static string SettingsWindow_OpenSettingsFolder {
            get {
                return ResourceManager.GetString("SettingsWindow_OpenSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        public static string Tray_Bluetooth {
            get {
                return ResourceManager.GetString("Tray_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        public static string Tray_Communications {
            get {
                return ResourceManager.GetString("Tray_Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Tray_Recording {
            get {
                return ResourceManager.GetString("Tray_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound devices.
        /// </summary>
        public static string Tray_SoundDevices {
            get {
                return ResourceManager.GetString("Tray_SoundDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Tray_Sounds {
            get {
                return ResourceManager.GetString("Tray_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Uninstaller_Cancel {
            get {
                return ResourceManager.GetString("Uninstaller_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Uninstaller_Caption_Close {
            get {
                return ResourceManager.GetString("Uninstaller_Caption_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove the installed copy of VolumeTrayAppWPF and its registration in Windows Apps. Choose what to do with your settings..
        /// </summary>
        public static string Uninstaller_DefaultDescription {
            get {
                return ResourceManager.GetString("Uninstaller_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove the VolumeTrayAppWPF folder under %LOCALAPPDATA%, including settings.xml..
        /// </summary>
        public static string Uninstaller_DeleteSettings_DefaultDescription {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also remove &quot;{0}&quot; including settings.xml..
        /// </summary>
        public static string Uninstaller_DeleteSettings_Description_Format {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_Description_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my settings.
        /// </summary>
        public static string Uninstaller_DeleteSettings_Title {
            get {
                return ResourceManager.GetString("Uninstaller_DeleteSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove VolumeTrayAppWPF installed at &quot;{0}&quot; and its entry in Windows Settings &gt; Apps. Choose what to do with your settings..
        /// </summary>
        public static string Uninstaller_Description_Format {
            get {
                return ResourceManager.GetString("Uninstaller_Description_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave settings.xml in place so a future install picks them up..
        /// </summary>
        public static string Uninstaller_KeepSettings_Description {
            get {
                return ResourceManager.GetString("Uninstaller_KeepSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep my settings.
        /// </summary>
        public static string Uninstaller_KeepSettings_Title {
            get {
                return ResourceManager.GetString("Uninstaller_KeepSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall VolumeTrayAppWPF.
        /// </summary>
        public static string Uninstaller_SectionHeader {
            get {
                return ResourceManager.GetString("Uninstaller_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall VolumeTrayAppWPF.
        /// </summary>
        public static string Uninstaller_Title {
            get {
                return ResourceManager.GetString("Uninstaller_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstaller_UninstallButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Uninstaller_UninstallingButton {
            get {
                return ResourceManager.GetString("Uninstaller_UninstallingButton", resourceCulture);
            }
        }
    }
}
